registries:
  'https://npm.jsr.io/':
    scopes: ['@jsr']

trustPolicy: 'no-downgrade'
trustPolicyIgnoreAfter: 10080

overrides:
  '@types/estree': '1.0.6'

allowBuilds:
  'core-js-pure': true
  'dtrace-provider': true
  'esbuild': true
  'sharp': false
  'unrs-resolver': true
  'workerd': true

minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@atcute/*'
  - '@oomfware/*'
  - '@mary-ext/*'
  - '@jsr/mary__*'
  - vite@8.3.3

patchedDependencies:
  '@vanilla-extract/css': patches/@vanilla-extract__css.patch
  wordgard: patches/wordgard.patch
