registries:
  'https://npm.jsr.io/':
    scopes: ['@jsr']

trustPolicy: 'no-downgrade'
trustPolicyIgnoreAfter: 10080

overrides:
  '@types/estree': '1.0.6'

allowBuilds:
  'core-js-pure': true
  'dtrace-provider': true
  'esbuild': true
  'sharp': false
  'unrs-resolver': true
  'workerd': true

minimumReleaseAgeExclude:
  - '@atcute/*'
  - '@oomfware/*'
  - '@mary-ext/*'
  - '@jsr/mary__*'
  - '@vitejs/plugin-react@6.1.0'
  - 'rolldown'
  - '@rolldown/*'

patchedDependencies:
  '@base-ui/react': patches/@base-ui__react.patch
  '@vanilla-extract/css': patches/@vanilla-extract__css.patch
