nodeLinker: 'hoisted'
autoInstallPeers: true
strictPeerDependencies: false
trustPolicy: 'no-downgrade'
trustPolicyIgnoreAfter: 10080
overrides:
  '@react-native/normalize-colors': '0.81.5'
  '@types/estree': '1.0.6'
  'metro': '0.83.3'
  'metro-config': '0.83.3'
  'metro-core': '0.83.3'
  'metro-runtime': '0.83.3'
  'metro-source-map': '0.83.3'
allowBuilds:
  'core-js-pure': true
  'dtrace-provider': true
  'esbuild': true
  'sharp': false
  'unrs-resolver': true
  'workerd': true
minimumReleaseAgeExclude:
  - '@atcute/*'
  - '@oomfware/*'
  - '@mary-ext/*'
patchedDependencies:
  '@base-ui/react': patches/@base-ui__react.patch
  '@react-navigation/native-stack': patches/@react-navigation__native-stack.patch
  '@vanilla-extract/css': patches/@vanilla-extract__css.patch
